CREATE TABLE [dbo].[MUserIcon]
(
	[UserID] INT NOT NULL,
	[IconId] INT NOT NULL

	CONSTRAINT FK_UserID_MU FOREIGN KEY (UserID) REFERENCES Users(UserID)
	CONSTRAINT FK_IconID_MU FOREIGN KEY (IconId) REFERENCES Icon(IconID)
)
