CREATE TABLE [dbo].[Users]
(
	UserID INT IDENTITY(1,1),
	Pseudo VARCHAR(25) NOT NULL UNIQUE,
	[Money] bigint NOT NULL DEFAULT 0,
	[Password] VARCHAR(50) NOT NULL,
	[Email] VARCHAR(200) NOT NULL,
	IP VARCHAR(50) NOT NULL,
	Level INT NOT NULL DEFAULT 1

	CONSTRAINT PK_Utilisateurid PRIMARY KEY (UserID)
)
